# image: "gitpod/workspace-node:latest"

# tasks:
#   - init: "npm install"

# vscode:
#   extensions:
#     - "esbenp.prettier-vscode"
#     - "NomicFoundation.hardhat-solidity"
#     - "ritwickdey.LiveServer"
